### ISSUE TITLE
URGENT: Token Validation Returning Error

### ISSUE THREAD

**Issue by mohamad-rmeity-cko** [checkout/checkout-sdk-net#184]
Hello,

Token validation is failing on new API key format. Unfortunately the merchant cannot upgrade to Release 3.0.0 of this SDK due to .NET Core limitations. They're currently on .NET Core 2.2, and if they wanna upgrade to SDK 3.0 then they will need to upgrade their .NET Core to 3.1 atleast. This upgrade will cause a lot of dependency issues which will in-turn cause a lot of delays and block the revenue from this merchant.

Can we enhance/change the SDK version 2.5.0 to accept other types of tokens in the API request?
This new format is already supported in release 3.0.0, with the below snippet:

`        private const string FourSecretKeyPattern = "^sk_(sbox_)?[a-z2-7]{26}[a-z2-7*#$=]$";
        private const string FourPublicKeyPatten = "^pk_(sbox_)?[a-z2-7]{26}[a-z2-7*#$=]$";

        public FourStaticKeysSdkCredentials(string secretKey, string publicKey)
            : base(PlatformType.Four,
                new Regex(FourSecretKeyPattern),
                new Regex(FourPublicKeyPatten),
                secretKey, publicKey)
        {
        }`

* Checkout SDK version: 2.5.0

When we try to use the new keys on the existing one (2.5.0), we get the below:
[System.FormatException: The format of value 'Bearer sk_sbox_uv435mpdzfdfmbzgvapjevxg6iz' is invalid.]
   at System.Net.Http.Headers.HeaderUtilities.CheckValidToken(String value, String parameterName)
   at System.Net.Http.Headers.AuthenticationHeaderValue..ctor(String scheme, String parameter)
   at System.Net.Http.Headers.AuthenticationHeaderValue..ctor(String scheme)
   at Checkout.SecretKeyCredentials.AuthorizeAsync(HttpRequestMessage httpRequest)

Can you please assist on this urgently? The merchant has been trying to upgrade with the new keys for a while, and this is causing a lot of failure.

Thanks

**Comment by rsaestrela** [comment]
Hi @mohamad-rmeity-cko. From version 3.5.1 we changed the existing setup and we started supporting `netstandard2.0` that should be compatible with .NET Core 2.2. In any case, we always recommend to stay up to date with the latest version 3.7.3. Would that solution work for you?
