### ISSUE TITLE
AggregateException at Checkout.ApiClient.<ValidateResponseAsync>d__13.MoveNext()

### ISSUE THREAD

**Issue by deepaknsp11** [checkout/checkout-sdk-net#254]
AggregateException at Checkout.ApiClient.<ValidateResponseAsync>d__13.MoveNext()

### Environment

* Checkout SDK version: 3.8.4
* Platform and version: Microsoft windows
* Operating System and version: Windows 10

### Description

While making the below call:
Dim tasks = Task.Run(Function() api.PaymentsClient().GetPaymentDetails('sessionid'))
tasks.Wait()
I am getting the exception.
Exception information:
    Exception type: AggregateException
    Exception message: One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at policyoptions.Page_Load(Object sender, EventArgs e)
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

The API response status code (404) does not indicate success.
   at Checkout.ApiClient.<ValidateResponseAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Checkout.ApiClient.<SendRequestAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Checkout.ApiClient.<Get>d__4`1.MoveNext()

### Current behavior

Occasionally it is sending exception while making get payment details call based on session id 

### Steps to reproduce

While making the below call:
Dim tasks = Task.Run(Function() api.PaymentsClient().GetPaymentDetails('sessionid'))
tasks.Wait()

### Possible solution

Could you please let me know what is reason of this exception and why it is happening.

- [ ] I may be able to implement this bug fix

**Comment by Armando-Ibarra** [comment]
AggregateException is often used for catching exceptions, that might occur when waiting for a Task to complete. Because Task in general can consist of multiple others, and this is not likely a SDK error.

404 Means not found, which probably you are not creating properly the payment before so that you are not able to retrieve payment details.

**Comment by Armando-Ibarra** [comment]
Let us know if you have any other issue, or re open this issue if needed.
